---
- name: this playbook for configuring all tools like jenkins,Trivy,Sonarqube
  hosts: localhost
  become: true

  tasks:
    - name: update machine 
      apt:
        name: "*"
        state: present
      
    

    - name: URL for jenkins 
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins.gpg

    - name: Add specified repository into sources list using specified filename
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary
        state: present
        filename: jenkins.list
    
    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-17-jre
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes


# installing Trivy 
    
    
    - name: install trivy uri
      ansible.builtin.get_url:
        url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
        dest: /tmp/trivy_0.18.3_Linux-64bit.deb
    
    - name: Install Trivy using dpkg
      apt:
        deb: /tmp/trivy_0.18.3_Linux-64bit.deb
        update_cache: yes

# installing docker 
    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    
    - name: repo install
      ansible.built.get_repository:
       repo: deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" 
       state: present 
       filename: docker.list

    - name: packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - container.io
          - docker-buildx-plugin
          - docker-compose-plugin 
        state: present
    - name : install dokcer package
      systemd:
        name: docker.io
        state: started
        enabled: yes

    - name: Set permissions on Docker socket
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0777'
    
    # run sonarqube container.io

    - name: run sonarqube container
      docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        ports:
          - "9000:9000"
    
   

      