---
- name: Configure Jenkins, Trivy, SonarQube, and Docker
  hosts: localhost
  remote_user: ubuntu
  become: true

  tasks:
    # Update package index
    - name: Update package index
      ansible.builtin.apt:
        update_cache: yes

    # Add Jenkins repository GPG key
    - name: Add Jenkins repository GPG key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins.gpg

    # Add Jenkins repository
    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary
        state: present
        filename: jenkins-stable

    # Install Jenkins
    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    # Start Jenkins service
    - name: Start Jenkins service
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: yes

    # Install Trivy
    - name: Download Trivy package
      ansible.builtin.get_url:
        url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
        dest: /tmp/trivy_0.18.3_Linux-64bit.deb

    - name: Install Trivy using dpkg
      ansible.builtin.apt:
        deb: /tmp/trivy_0.18.3_Linux-64bit.deb

    # Install Docker
    - name: Install prerequisite packages for Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Set permissions on Docker socket
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0777'

    # Run SonarQube container
    - name: Run SonarQube container
      community.docker.docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        ports:
          - "9000:9000"
