---
- name: This playbook for configuring all tools like Jenkins, Trivy, SonarQube
  hosts: localhost
  become: true

  tasks:
    - name: Update machine
      apt:
        name: "*"
        state: latest
      
    - name: URL for Jenkins
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        dest: /usr/share/keyrings/jenkins.gpg

    - name: Add Jenkins repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins.gpg] http://pkg.jenkins.io/debian-stable binary
        state: present
        filename: jenkins.list
    
    - name: Install fontconfig
      apt:
        name: fontconfig
        state: present

    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-17-jre
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

# Installing Trivy
    - name: Download Trivy package
      ansible.builtin.get_url:
        url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
        dest: /tmp/trivy_0.18.3_Linux-64bit.deb

    - name: Install Trivy using apt
      ansible.builtin.apt:
        deb: /tmp/trivy_0.18.3_Linux-64bit.deb
        update_cache: yes


# Installing Docker
    - name: Install prerequisite packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create directory for Docker GPG key
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present
        filename: docker.list

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Set permissions on Docker socket
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0777'

# Running SonarQube container

    - name: Run SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:lts-community
        state: started
        ports:
          - "9000:9000"
